services:
  - type: web
    name: lendnlearn
    env: docker
    plan: free
    envVars:
      - key: DB_HOST
        value: aws-0-ap-south-1.pooler.supabase.com
      - key: DB_PORT
        value: "6543"
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres.bpmpidpftytimisafyem
      - key: DB_PASS
        sync: false # Enter your Supabase database password in Render's dashboard
